[package]
name = "hexput-plugin"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
hexput-parser = { path = "../hexput-parser" }
hexput-globalvar = { path = "../hexput-globalvar" }
hexput-exec = { path = "../hexput-exec" }
hexput-check = { path = "../hexput-check" }

[lints]
workspace = true
